name: aws_s3_upload
description: A simple, convenient package for uploading to S3.
version: 1.4.0
homepage: https://github.com/Serdnad/aws_s3_upload

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  amazon_cognito_identity_dart_2: ^1.0.3
  http: ^0.13.3
  path: ^1.8.0
